#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: "$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10 | md5sum | head -c 8)"
    username: JuiceWorks Admin
    password: "$6$rounds=4096$abc$def12345" # Encrypted password for admin user
  user-data:
    disable_root: false
    users:
      - name: adminuser
        gecos: "Admin User"
        primary_group: "adm"
        groups: [sudo, adm]
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: "$6$rounds=4096$abc$def12345" # Encrypted password for admin user
      - name: JuiceWorks Student
        gecos: "Normal User"
        primary_group: "users"
        groups: []
        lock_passwd: false
        passwd: "$6$rounds=4096$xyz$ghi67890" # Encrypted password for normal user
